"""Domain service interfaces."""

from typing import Protocol, List, Optional
from .models import ConnectionInfo, ProcessStatus


class IProcessService(Protocol):
    def get_status(self, process_name: str) -> ProcessStatus: ...
    def get_pid(self, process_name: str) -> Optional[int]: ...
    def get_priority(self, process_name: str) -> str: ...
    def get_affinity(self, process_name: str) -> List[int]: ...
    def set_priority(self, process_name: str, high: bool) -> bool: ...
    def set_affinity(self, process_name: str, cores: List[int]) -> bool: ...
    def is_admin(self) -> bool: ...


class INetworkService(Protocol):
    def get_connections(self, pid: int) -> List[ConnectionInfo]: ...


class IOptimizerService(Protocol):
    def clear_cache(self) -> tuple[bool, str]: ...
