"""Domain service interfaces."""

from typing import Protocol

from .models import ConnectionInfo, ProcessStatus


class IProcessService(Protocol):
    def get_status(self, process_name: str) -> ProcessStatus: ...
    def get_pid(self, process_name: str) -> int | None: ...
    def get_priority(self, process_name: str) -> str: ...
    def get_affinity(self, process_name: str) -> list[int]: ...
    def set_priority(self, process_name: str, priority: str) -> bool: ...
    def set_affinity(self, process_name: str, cores: list[int]) -> bool: ...
    def is_admin(self) -> bool: ...


class ISystemService(Protocol):
    def get_cpu_count(self) -> int: ...
    def get_system_memory(self) -> tuple[float, float]: ...
    def get_system_cpu(self) -> float: ...
    def get_system_cpu_temperature(self) -> float | None: ...


class IGpuService(Protocol):
    def is_available(self) -> bool: ...
    def get_system_vram_usage(self) -> tuple[float, float]: ...
    def get_system_gpu_temperature(self) -> float | None: ...
    def get_system_gpu_usage(self) -> float | None: ...
    def shutdown(self) -> None: ...


class INetworkService(Protocol):
    def get_connections(self, pid: int) -> list[ConnectionInfo]: ...
